title: Angst and Apathy
description: > # this means to ignore newlines until "baseurl:"
  A blog about stuff
permalink: ':title/'
baseurl: "/angstandapathy.github.io" # the subpath of your site, e.g. /blog
url: "http://angstandapathy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Peter # add your name
author-img: pic.jpg # add your photo
about-author:  An attempt at organizing my thoughts. # add description
social-twitter: /petercskog # add your Twitter handle
social-facebook: /peter.c.skog # add your Facebook handle
social-github: /angstandapathy # add your Github handle
social-linkedin: /peter-skog-048602166/ # add your Linkedin handle
social-email: angstandapathyblog@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
